name: Publish to NPM
on:
  push:
    branches: ["main"]

jobs:
  publishToNPM:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Run build
        uses: borales/actions-yarn@v5
        with:
          cmd: build

      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
